# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interfaces/chatserver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from interfaces import globalmessage_pb2 as interfaces_dot_globalmessage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='interfaces/chatserver.proto',
  package='chatsystem',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1binterfaces/chatserver.proto\x12\nchatsystem\x1a\x1einterfaces/globalmessage.proto2\xae\x01\n\nChatServer\x12\x33\n\nChatStream\x12\x11.chatsystem.Group\x1a\x10.chatsystem.Note0\x01\x12/\n\x08SendNote\x12\x10.chatsystem.Note\x1a\x11.chatsystem.Empty\x12:\n\nGetHistory\x12\x18.chatsystem.GroupHistory\x1a\x10.chatsystem.Note0\x01\x62\x06proto3'
  ,
  dependencies=[interfaces_dot_globalmessage__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CHATSERVER = _descriptor.ServiceDescriptor(
  name='ChatServer',
  full_name='chatsystem.ChatServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=76,
  serialized_end=250,
  methods=[
  _descriptor.MethodDescriptor(
    name='ChatStream',
    full_name='chatsystem.ChatServer.ChatStream',
    index=0,
    containing_service=None,
    input_type=interfaces_dot_globalmessage__pb2._GROUP,
    output_type=interfaces_dot_globalmessage__pb2._NOTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendNote',
    full_name='chatsystem.ChatServer.SendNote',
    index=1,
    containing_service=None,
    input_type=interfaces_dot_globalmessage__pb2._NOTE,
    output_type=interfaces_dot_globalmessage__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetHistory',
    full_name='chatsystem.ChatServer.GetHistory',
    index=2,
    containing_service=None,
    input_type=interfaces_dot_globalmessage__pb2._GROUPHISTORY,
    output_type=interfaces_dot_globalmessage__pb2._NOTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVER)

DESCRIPTOR.services_by_name['ChatServer'] = _CHATSERVER

# @@protoc_insertion_point(module_scope)
